name: flutter_v2ex
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.2.2

environment:
    sdk: ">=2.18.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.

    # 动态取色
    dynamic_color: ^1.6.2

    # 网络请求
    dio: ^4.0.6
    cookie_jar: ^3.0.1
    #    dio_http_cache: ^0.3.0
    dio_http2_adapter: ^2.0.0
    dio_http_cache:
        git:
            url: https://github.com/guozhigq/dio-http-cache.git
    dio_cookie_manager: ^2.0.0

    # dom解析渲染
    html: ^0.15.1
    webfeed_plus: ^1.0.0
    flutter_html: 3.0.0-alpha.6
    flutter_html_table: ^3.0.0-alpha.4
    flutter_html_iframe: ^3.0.0-alpha.4

    # webView
    url_launcher: ^6.1.9
    flutter_inappwebview: ^6.0.0-beta.22

    # 图片&保存
    extended_image: ^7.0.2
    cached_network_image: ^3.2.3
    image_gallery_saver: ^1.7.1

    # 下拉刷新
    easy_refresh: ^3.2.2
    # 动画
    animations: ^2.0.7
    # toast提示
    flutter_smart_dialog: ^4.8.1
    # 设备信息
    device_info_plus: ^8.2.0
    get: ^4.6.5

    # 数据缓存
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    path_provider: ^2.0.12
    get_storage: ^2.0.3

    # 权限
    permission_handler: ^10.2.0
    # 桌面长按菜单
    quick_actions: ^1.0.1
    # 通知
    flutter_local_notifications: ^13.0.0
    # 时区
    timezone: ^0.9.1
    # 代理
    system_proxy: ^0.1.0
    # 分享
    share_plus: ^6.3.1

    extended_tabs: ^4.0.2
    extended_text_field: ^11.0.1
    sticky_headers: ^0.3.0+2

    # 外观
    container_tab_indicator: ^0.3.0
    # 响应式
    flutter_adaptive_scaffold: ^0.1.2

    scroll_to_index: ^3.0.1
    google_fonts: ^4.0.3

dev_dependencies:
    flutter_test:
        sdk: flutter

    # The "flutter_lints" package below contains a set of recommended lints to
    # encourage good coding practices. The lint set provided by the package is
    # activated in the `analysis_options.yaml` file located at the root of your
    # package. See that file for information about deactivating specific lint
    # rules and activating additional ones.
    flutter_lints: ^2.0.0
    #    flutter_launcher_icons: ^0.9.3
    hive_generator: ^2.0.0
    build_runner: ^2.3.3

flutter_icons:
    android: true
    ios: true
    remove_alpha_ios: true
    image_path: assets/images/icon/icon_launcher.png
    image_path_android: assets/images/icon/icon_android.png
    image_path_ios: assets/images/icon/icon_ios.png
    adaptive_icon_background: "#3A699A"
    adaptive_icon_foreground: assets/images/icon/ic_launcher_foreground.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/sound/
        - assets/images/
        - assets/images/social/

    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
#    fonts:
#        - family: NotoSansSC
#          fonts:
#              - asset: assets/fonts/NotoSansSC/NotoSansSC-Black.otf
#              - asset: assets/fonts/NotoSansSC/NotoSansSC-Bold.otf
#              - asset: assets/fonts/NotoSansSC/NotoSansSC-Light.otf
#              - asset: assets/fonts/NotoSansSC/NotoSansSC-Medium.otf
#              - asset: assets/fonts/NotoSansSC/NotoSansSC-Regular.otf
#              - asset: assets/fonts/NotoSansSC/NotoSansSC-Thin.otf
#                style: italic

# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
